### PR TITLE
Code: Move beatmap difficulty enum.

### PR DESCRIPTION
**Pull request by TheVileOne**

### CODE REVIEW

**Comment by peppy** [comment]
I don't even get the point of this, to be honest. Want to explain the meaning behind moving this?

**Comment by TheVileOne** [comment]
I moved the difficulty parse logic from AICompose to Beatmap. I felt it could be more useful there and would avoid dealing with raw star values.

**Comment by peppy** [comment]
Updating the sdk just for something like this seems completely poitnless. if this was being used by others their apps would suddenly completely break. Please only make changes if tehre's a reason to do so (especially when they are not backwards comaptible).sd

**Comment by TheVileOne** [comment]
Fine. I can include an AiMod reference in Beatmap and it will work just fine.

**Pull request closed without merging**
